### ISSUE TITLE
3 digit codes

### ISSUE THREAD

**Issue by luckman212** [squatto/alfred-imessage-2fa#21]
Hi Scott- just making sure you saw my PR #19 about 3 digit codes. [quick fix to find 3-digit codes e.g. Zocdoc](https://github.com/squatto/alfred-imessage-2fa/pull/19)

**Comment by squatto** [comment]
I did (thank you!) but I haven't had a chance to test it out. I've avoided 3 and 4 digit codes because they tend to capture years and phone numbers, but I think that requiring them to be right after "code" or "is" will likely take care of that. It will still match stuff like "the year is 2021" but I think that's an edge case, ultimately.

Let me give it a quick test 👍🏻
